### ISSUE TITLE
License details

### ISSUE THREAD

**Issue by fabaff** [madpilot/amberelectric.py#4]
Please add a license statement and a LICENSE file to the repo.

Thanks

**Comment by onkelbeh** [comment]
Hi,

first, thanks for your work. I would like to include your library in my Home Assistant Gentoo overlay, https://github.com/onkelbeh/HomeAssistantRepository/, because it is actively used by an integration.

Same here, you have not selected a license, not here, and not on pypi, so I am also asking for clarification.
According to Gentoo's license guidelines, it is not allowed to redistribute a package without a license (https://devmanual.gentoo.org/general-concepts/licenses/index.html).

Today, I added your integration with an "all-rights-reserved" tag, but this forbids redistribution and usage of gentoo's mirror system.

At the bottom of my [README.md](https://github.com/onkelbeh/HomeAssistantRepository/blob/master/README.md) you can find some license stats, perhaps this helps your decision. Thanks a lot in advance.

\B.

**Comment by madpilot** [comment]
Added Apache-2.0 License
